#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  vars:
    vundle_repo_url: https://github.com/VundleVim/Vundle.vim.git
    rustup_install_script_url: https://sh.rustup.rs
  tasks:
  - name: Updating Base System
    apt:
      upgrade: dist
      update_cache: yes
      autoclean: yes
      autoremove: yes
  - name: Installing Core Packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
        - ack # better grep
        - aria2 # wget but faster
        - birthday # track birthdays
        - calcurse # curses calendar
        - cmus # terminal audio player
        - curl # do you really need anything else?
        - gcc
        - git
        - htop
        - jq # json sed
        - lftp # ftp client
        - locate # find file by regex
        - man
        - mtr # network troubleshooting
        - mutt # email in terminal
        - mycli # mysql client with autocomplete
        - neovim # Refactored rewrite of vim
        - newsbeuter # terminal rss reader
        - nmap # network probe tool
        - peco # interactive recursive grep
        - pgcli # postgres client with autocomplete
        - pydf # disk usage visualizer
        - qalc # bc but good
        - rsync # resumeable file transfers over network
        - screenfetch # Prints system info to screen
        - ssh # telnet++
        - tpp # terminal powerpoint presentor
        - tmux # terminal multiplexing
        - tig # terminal git graph explorer
        - tree # visualize filesystem recursively
        - weechat # IRC

  - name: Installing Vundle
    git:
      repo: "{{ vundle_repo_url }}"
      dest: "~/.vim/bundle/Vundle.vim"

  - name: Installing NeoVim Plugins
    shell: "vim +BundleInstall +qall"

  - name: Install Rust Toolchain
    vars:
      working_dir: "/tmp"
      install_script_path: "{{ working_dir }}/rustup.sh"
    block:
      - name: Download Rustup Install Script
        get_url:
          url:   "{{ rustup_install_script_url }}"
          dest: "{{ install_script_path }}"
      - name: Run Rustup Install Script
        shell: "sh {{ install_script_path }} -y --default-toolchain nightly"
    always:
      - name: Remove Rustup Install Script
        file:
          path: "{{ install_script_path }}"
          state: absent
