#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  vars:
    vundle_repo_url: https://github.com/VundleVim/Vundle.vim.git
    rustup_install_script_url: https://sh.rustup.rs
  tasks:
  - name: Updating Base System
    apt:
      upgrade: dist
      update_cache: yes
      autoclean: yes
      autoremove: yes
  - name: Installing Core Packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
        - curl
        - gcc
        - git
        - htop
        - man
        - nmap
        - screenfetch
        - ssh
        - neovim
        - wget

  - name: Installing Vundle
    git:
      repo: "{{ vundle_repo_url }}"
      dest: "~/.vim/bundle/Vundle.vim"

  - name: Installing NeoVim Plugins
    shell: "vim +BundleInstall +qall"

  - name: Install Rust Toolchain
    vars:
      working_dir: "/tmp"
      install_script_path: "{{ working_dir }}/rustup.sh"
    block:
      - name: Download Rustup Install Script
        get_url:
          url:   "{{ rustup_install_script_url }}"
          dest: "{{ install_script_path }}"
      - name: Run Rustup Install Script
        shell: "sh {{ install_script_path }} -y --default-toolchain nightly"
    always:
      - name: Remove Rustup Install Script
        file:
          path: "{{ install_script_path }}"
          state: absent
